openapi: 3.0.3
info:
  title: API for NewsletterManager
  description: This is testing Go project.
  version: 0.0.0
servers:
  - url: https://localhost:8080
    description: Main production server

tags:
  - name: session
    description: Sessions API
  - name: newsletter
    description: Newsletters API
  - name: email
    description: Emails API
  - name: subscription
    description: Subscriptions API

paths:
  /api/v1/authors/sign-in:
    $ref: './v1/paths/session.yaml#/NativeSessions'
  /api/v1/authors/sign-up:
    $ref: './v1/paths/author.yaml#/AuthorSignUp'
  /api/v1/authors/current/refresh-token:
    $ref: './v1/paths/session.yaml#/RefreshSessions'
  /api/v1/authors/current/logout:
    $ref: './v1/paths/session.yaml#/DestroySessions'
  /api/v1/authors/current/change-password:
    $ref: './v1/paths/author.yaml#/ChangeAuthorPassword'
  /api/v1/authors/current:
    $ref: './v1/paths/author.yaml#/CurrentAuthor'
  /api/v1/authors/current/newsletters:
    $ref: './v1/paths/newsletter.yaml#/Newsletters'
  /api/v1/newsletters/{newsletterId}:
    $ref: './v1/paths/newsletter.yaml#/Newsletter'

  /api/v1/emails/{emailId}:
    $ref: './v1/paths/email.yaml#/Email'
  /api/v1/newsletters/{newsletterId}/emails:
    $ref: './v1/paths/email.yaml#/Emails'

  /api/v1/newsletters:
    $ref: './v1/paths/newsletter.yaml#/ListNewsletters'
  /api/v1/newsletters/{newsletterId}/subscribe:
    $ref: './v1/paths/subscription.yaml#/Subscribe'
  /api/v1/newsletters/{newsletterId}/unsubscribe:
    $ref: './v1/paths/subscription.yaml#/Unsubscribe'
  /api/v1/newsletters/{newsletterId}/subscriptions:
    $ref: './v1/paths/subscription.yaml#/NewsletterSubscriptions'
  /api/v1/subscriptions:
    $ref: './v1/paths/subscription.yaml#/SubscriptionsByEmail'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
