/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventJoinReq struct {
	// IDs of question options for specified event that the user has chosen
	OptionIds []string `json:"optionIds,omitempty"`
}
