/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UploadImageResp struct {
	// Image ID
	Id string `json:"id"`
	// URL where the image should be uploaded to, using PUT request
	Url string `json:"url"`
}
