/*
 * API for NewsletterManager
 *
 * This is testing Go project.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Session object for creating a stateless session
type CreateSessionInput struct {
	Email string `json:"email"`
	Password string `json:"password"`
}
