/*
 * API for NewsletterManager
 *
 * This is testing Go project.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiError struct {
	// Request ID
	RequestId string `json:"requestId"`
	// Error code
	ErrorCode string `json:"errorCode"`
	// Public human readable error message
	ErrorMessage string `json:"errorMessage,omitempty"`
	// Error data
	ErrorData *interface{} `json:"errorData,omitempty"`
}
