/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Score struct {
	Participant *Participant `json:"participant,omitempty"`
	// the average score of the last five games
	Score float32 `json:"score"`
}
