/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// EventCategory : The category of the event
type EventCategory string

// List of EventCategory
const (
	CELEBRATION_EventCategory EventCategory = "celebration"
	SPORT_EventCategory       EventCategory = "sport"
	MEETUP_EventCategory      EventCategory = "meetup"
	OTHER_EventCategory       EventCategory = "other"
)
