/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ParticipantWithAnswers struct {
	Participant *Participant `json:"participant"`
	Answers     *[]Answer    `json:"answers"`
}
