/*
 * API for NewsletterManager
 *
 * This is testing Go project.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Newsletter object for creating a newsletter
type CreateNewsletterReq struct {
	Name string `json:"name"`
	Description string `json:"description"`
}
