/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserUpdateReq struct {
	// User full name
	Name string `json:"name,omitempty"`
	// User's instagram
	Instagram string `json:"instagram,omitempty"`
	// User's linkedin
	Linkedin string `json:"linkedin,omitempty"`
	// ID of image from `POST /api/v1/users/current/upload-image`
	ImageId string `json:"imageId,omitempty"`
}
