/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// EventSize : The size of the event
type EventSize string

// List of EventSize
const (
	SIZE_TO10_EventSize   EventSize = "sizeTo10"
	SIZE10_TO30_EventSize EventSize = "size10To30"
	SIZE31_TO50_EventSize EventSize = "size31To50"
)
