/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Question for event game that the organizer has chosen (or can choose)
type EventQuestion struct {
	Id       string         `json:"id"`
	Text     string         `json:"text"`
	Category *EventCategory `json:"category,omitempty"`
}
