/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	// User ID
	Id string `json:"id"`
	// User full name
	Name string `json:"name"`
	// User's instagram
	Instagram string `json:"instagram,omitempty"`
	// User's linkedin
	Linkedin string `json:"linkedin,omitempty"`
	// link to user profile image
	ImageUrl string `json:"imageUrl"`
	// Whether the user finished registration. False for newly created users, true if update `PUT /api/v1/users/current` endpoint was called for existing user (i.e. they confirmed their profile info).
	Finalized bool `json:"finalized"`
	// Whether the user is using useful authentication provider, which enables them to be organizer of events. False for anonymous (guest) users.
	StrongAuth bool `json:"strongAuth"`
}
