/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Participant struct {
	// User ID
	Id string `json:"id"`
	// User full name
	Name string `json:"name"`
	// User's instagram
	Instagram string `json:"instagram,omitempty"`
	// User's linkedin
	Linkedin string `json:"linkedin,omitempty"`
	// Link to user profile image
	ImageUrl string `json:"imageUrl"`
}
