/*
 * API for NewsletterManager
 *
 * This is testing Go project.
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Session object
type CreateAuthorResp struct {
	Author *Author `json:"author"`
	Session *Session `json:"session"`
}
