/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Answer struct {
	// ID of question
	QuestionId string `json:"questionId"`
	// ID of selected option
	OptionId string `json:"optionId"`
}
