/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ApiError struct {
	// Request ID
	RequestId string `json:"requestId"`
	// Error code
	ErrorCode string `json:"errorCode"`
	// Public human readable error message
	ErrorMessage string `json:"errorMessage,omitempty"`
	// Any additional structured error data
	ErrorData *interface{} `json:"errorData,omitempty"`
}
