/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ScoreReq struct {
	// amount of questions the user correctly answered during the game round
	Score int32 `json:"score"`
}
