/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// GameType : Type of the event's game
type GameType string

// List of GameType
const (
	EVENT_MATCH_GameType  GameType = "eventMatch"
	LET_ME_GUESS_GameType GameType = "letMeGuess"
)
