/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EventWithStatus struct {
	Event *Event `json:"event,omitempty"`
	// User has already joined the event (false for not authenticated users)
	AlreadyJoined bool `json:"alreadyJoined,omitempty"`
	// Event reaches its full capacity
	IsFull bool `json:"isFull,omitempty"`
}
