/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type CreateEventReq struct {
	// Title name of the event
	Title    string         `json:"title"`
	Category *EventCategory `json:"category"`
	// The location of an event or the link
	Location string     `json:"location,omitempty"`
	Size     *EventSize `json:"size"`
	// ID of uploaded image (only one of imageId and staticImageId should be non-null). Use it only if you already have ID of uploaded event image.
	ImageId string `json:"imageId,omitempty"`
	// ID of static image on frontend (only one of imageId and staticImageId should be non-null)
	StaticImageId string `json:"staticImageId,omitempty"`
	// Start time of the real-life event (not the game)
	StartTime time.Time `json:"startTime"`
	// End time of the real-life event (not the game)
	EndTime  time.Time `json:"endTime"`
	GameType *GameType `json:"gameType"`
	// IDs of questions for specified event category that the organizer has chosen
	QuestionIds []string `json:"questionIds"`
}
