/*
 * IceBreaker API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

type Event struct {
	// Event ID
	Id string `json:"id"`
	// Title name of the event
	Title    string         `json:"title"`
	Category *EventCategory `json:"category"`
	Size     *EventSize     `json:"size"`
	// The optional location or link
	Location string `json:"location"`
	// The event image URL
	ImageURL string `json:"imageURL,omitempty"`
	// ID of static image on frontend (only one of imageId and staticImageId should be non-null)
	StaticImageId string `json:"staticImageId,omitempty"`
	// Start time of the real-life event (not the game)
	StartTime time.Time `json:"startTime"`
	// End time of the real-life event (not the game)
	EndTime time.Time `json:"endTime"`
	// Code for joining and generating share dynamic links. Only available if the requesting user is an organizer
	Code string `json:"code,omitempty"`
	// The event has been canceled.
	IsCanceled bool `json:"isCanceled,omitempty"`
	// Dynamic links for sharing. Only available if the requesting user is an organizer
	ShareLink string     `json:"shareLink,omitempty"`
	GameType  *GameType  `json:"gameType"`
	Organizer *Organizer `json:"organizer"`
}
