BEGIN;

CREATE TYPE user_role AS ENUM ('user', 'admin');

CREATE TABLE "user" (
    id            UUID         PRIMARY KEY,
    referrer_id   UUID         REFERENCES "user" (id),
    name          VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          user_role    NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL
);

CREATE TABLE refresh_token (
    id         VARCHAR(255) PRIMARY KEY,
    user_id    UUID         NOT NULL REFERENCES "user" (id) ON DELETE CASCADE,
    expires_at TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

COMMENT ON COLUMN refresh_token.id IS 'Cryptographically secure string generated by the application. Safe to be used by clients.';

COMMIT;
