BEGIN;

CREATE TABLE "author" (
    "id" UUID PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "password_hash" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE newsletter (
    "id" UUID PRIMARY KEY,
    "author_id" UUID NOT NULL REFERENCES "author" (id) ON DELETE CASCADE,
    "name" VARCHAR(255) NOT NULL,
    "description" VARCHAR(255) NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

CREATE TABLE email (
    "id" UUID PRIMARY KEY,
    "newsletter_id" UUID NOT NULL REFERENCES "newsletter" (id) ON DELETE CASCADE,
    "subject" VARCHAR(255) NOT NULL,
    "html_content" VARCHAR(1024) NOT NULL,
    "created_at" TIMESTAMP NOT NULL
);

CREATE TABLE refresh_token (
    id         VARCHAR(255) PRIMARY KEY,
    author_id    UUID         NOT NULL REFERENCES "author" (id) ON DELETE CASCADE,
    expires_at TIMESTAMP    NOT NULL,
    created_at TIMESTAMP    NOT NULL
);

COMMENT ON COLUMN refresh_token.id IS 'Cryptographically secure string generated by the application. Safe to be used by clients.';

COMMIT;
