name: Build

on:
  push:
    tags:
      - '*'

env:
  AWS_REGION: us-east-1
  # ECR_REPOSITORY: '' # FIXME: Required

jobs:
  image:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT for the OIDC
      contents: read  # This is required for actions/checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region:     ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/CICD
          role-session-name: "GitHubWorkflowCI"
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_TAG: ${{ github.ref_name }}
        run: |
          APP_VERSION=${GIT_TAG#v}
          IMAGE_TAG=$APP_VERSION
          docker build --build-arg APP_VERSION=$APP_VERSION -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
