name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Go
        uses: ./.github/actions/setup-go
      - name: Create release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: ${{ github.ref_name }}
          files: |
            CHANGELOG.md
            ./api/http/openapi.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
